name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Production Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: archie0223/devops-assessment:prod  # 修改为你的用户名和仓库名

  build_dev:
    runs-on: ubuntu-latest
    needs: build_prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Development Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: archie0223/devops-assessment:dev  # 修改为你的用户名和仓库名

  test:
    runs-on: ubuntu-latest
    needs: [build_prod, build_dev]
    steps:
      - name: Run Tests
        run: |
          echo "Testing build success"
          docker pull archie0223/devops-assessment:prod  # 使用实际的镜像地址
          docker pull archie0223/devops-assessment:dev  # 使用实际的镜像地址
          echo "Both images were pulled successfully"
